### ISSUE TITLE
Not sure how to run this

### ISSUE THREAD

**Issue by PhilT** [jonarrien/telescope-cmdline.nvim#1]
Thanks for publishing this! I have a very wide screen and having a floating window for commands is ideal.

However, I'm not sure how to invoke it. Is it meant to override `:`? I've only just discovered Telescope (amazing!) so it's probably me but just wondering what I can do to get this to work. I'll dig around in the code but any ideas are welcome.

Cheers.

**Comment by jonarrien** [comment]
I intend to override `:`, but had some challenges and do not recommend mapping it yet. 
If you loaded the extension properly, then you can use any key mapping to trigger `:Telescope cmdline<CR>`.

**Comment by PhilT** [comment]
Aha! Thanks for that! Works a treat. My leader is spacebar so `<Leader>;` might be quite good.

Thanks again.
