### ISSUE TITLE
[Question] Change the position of the cmd line

### ISSUE THREAD

**Issue by AceCodePt** [jonarrien/telescope-cmdline.nvim#10]
How can I change the position of the cmd window to the bottom for example?

**Comment by jonarrien** [comment]
You can customise the window by changing the picker setting in telescope settings. For example, using `bottom_pane` layout strategy, or registering your own layout.

```lua
require('telescope').setup({
  extensions = {
      cmdline = {
        picker     = {
          layout_strategy = "bottom_pane"
        },
      },
  } 
})
```
