### ISSUE TITLE
Support fuzzy finding

### ISSUE THREAD

**Issue by dlvhdr** [jonarrien/telescope-cmdline.nvim#12]
Given the input "lsp" I would like to match commands such as "LspInfo".
Right now I have to match the casing and search for "Lsp".
Also fuzzy searching in general would help like typing "lsi" to find "**L** **s** p **I**nfo".

**Comment by jonarrien** [comment]
This plugin uses nvim's internal command line autocompletion and it will suggest the same results as command line does ( case sensitive and without fuzzy finding). On the other hand, it uses your input to search in command history and it won't work well with fuzzy finding. 

In any case, typing `lsp` provides the results what you are looking for. Just ensure you use `<TAB>` to autocomplete it.

<img width="827" alt="image" src="https://github.com/jonarrien/telescope-cmdline.nvim/assets/1249415/afc4693b-dc8b-4abb-9965-f3c0598f3e2c">
