### ISSUE TITLE
[BUG] Themes do not apply

### ISSUE THREAD

**Issue by JustBarnt** [jonarrien/telescope-cmdline.nvim#19]
I have tried to apply telescopes themes from `telescope.themes` and nothing applies them

**Comment by jonarrien** [comment]
I'm not using `telescope.themes`, but you can pass any telescope settings to the picker in the extension settings. 
Could you please provide some information on how are you trying to use it?

**Comment by JustBarnt** [comment]
I've tried both the way that `telescope.ui-select` does it and the way you do it with a normal picker. `Telescope cmdline` seems to only accept the customization to the `layout_config` properties

```lua
require('telescope').setup({
    defaults = {
        initial_mode = "insert",
    },
    extensions = {
        ["ui-select"] = {
            require("telescope.themes").get_cursor({ initial_mode = "normal" }),
        },
        cmdline = {
            --require("telescope.themes").get_ivy(),
            picker = {
                theme = "ivy",
                layout_config = {
                    width = 60,
                    height = 10,
                },
            },
        },
    },
    pickers = {
        buffers = {
            initial_mode = "normal",
            mappings = {
                i = {
                    ["<c-d>"] = actions.delete_buffer + actions.move_to_top,
                    ["<c-q>"] = actions.close,
                },
                n = {
                    ["d"] = actions.delete_buffer,
                },
            },
        },
        find_files = require("core.utils").select_find_command(), 
    },
})
```

**Comment by JustBarnt** [comment]
This is a printed table for the picker config that gets passed into telescope cmdline. The `ivy` theme is there, but it does not seem to apply the opts from picker outside of layout_config like I mentioned above, I also included trying to set the `initial_mode` as well which is also an option that can be passed to a `picker`

```lua
{
  completions = { "command" },
  highlights = {
    icon = "Include"
  },
  icons = {
    command = " ",
    history = " ",
    number = "󰴍 ",
    system = "",
    unknown = ""
  },
  mappings = {
    complete = "<Tab>",
    run_input = "<CR>",
    run_selection = "<C-CR>"
  },
  output_pane = {
    enabled = false
  },
  overseer = {
    enabled = true
  },
  picker = {
    initial_mode = "normal",
    layout_config = {
      height = 10,
      width = 60
    },
    theme = "ivy"
  }
}
```

**Comment by JustBarnt** [comment]
~@jonarrien I have figured out the issue, when you register the extension to telescope you are not passing the config given by the user, you are just passing `ext_config` instead of either merging the configs together, or using the users if config is not an empty table. I can submit a PR fixing this.~

Ignore this I was looking at the wrong thing...

**Comment by JustBarnt** [comment]
I do notice that you are not using `require 'telescope.config'.values` is there a reason why?

**Comment by jonarrien** [comment]
@JustBarnt you can apply ivy theme this way: 

```lua
require('telescope').setup({
    ...
    extensions = {
       ...
        cmdline = {
            picker = require("telescope.themes").get_ivy(), 
        },
    },
    ...
})
```
