### ISSUE TITLE
Cmd executing bug

### ISSUE THREAD

**Issue by iamgodot** [jonarrien/telescope-cmdline.nvim#21]
I'm using Nvim 0.9.5 installed via Homebrew on MacOS, and this plugin installed with Telescope as instructed in README via Lazy. 2 things are currently not working:

1. Executing commands such as `echo` or `pwd` won't print anything.
2. Executing bash commands such as `!ls` leads to following error:

```
E5108: Error executing lua: ...nvim/lazy/telescope-cmdline.nvim/lua/cmdline/actions.lua:44: nvim_exec2(): Vim:E492: Not an editor command: OverseerRunCmd ls
stack traceback:
        [C]: in function 'nvim_exec2'
        ...nvim/lazy/telescope-cmdline.nvim/lua/cmdline/actions.lua:44: in function 'run'
        ...nvim/lazy/telescope-cmdline.nvim/lua/cmdline/actions.lua:97: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```

**Comment by jonarrien** [comment]
1. `echo` and `pwd` commands are displayed in statusline. If you use `cmdheight=0`, like I do, it won't show anything. 
2. This plugin has overseer.nvim integration enabled by default and all commands starting with `!` needs that plugin. If you are not using, you can disable the integration with [this option](https://github.com/jonarrien/telescope-cmdline.nvim/blob/9d4ef3e16e117e7ce91cb335247c87fb8d744696/lua/cmdline/config.lua#L27). 

> NOTE: Disabling overseer.nvim may have other caveats. I'm checking what would be the best approach to unify the outputs.

**Comment by iamgodot** [comment]
> 1. `echo` and `pwd` commands are displayed in statusline. If you use `cmdheight=0`, like I do, it won't show anything.
> 2. This plugin has overseer.nvim integration enabled by default and all commands starting with `!` needs that plugin. If you are not using, you can disable the integration with [this option](https://github.com/jonarrien/telescope-cmdline.nvim/blob/9d4ef3e16e117e7ce91cb335247c87fb8d744696/lua/cmdline/config.lua#L27).
> 
> > NOTE: Disabling overseer.nvim may have other caveats. I'm checking what would be the best approach to unify the outputs.

Disabling overseer works fine now and I think it's better to mention it in README. Thanks, I'll close this now.
