### ISSUE TITLE
Neovim freezes when !

### ISSUE THREAD

**Issue by digital-deceit** [jonarrien/telescope-cmdline.nvim#23]
Thanks beforehand!

Every time I hit **!** neovim freezes for like 10-20 seconds. It keeps freezing every key I enter, even backspacing.

**Comment by jonarrien** [comment]
Can you provide a minimal config to reproduce the issue or some context about your current setup?

Some ideas:
* Check your neovim ~> `0.10.0`
* This plugin uses `overseer.nvim` integration by default. If you are not using this plugin, you disable it in telescope options. The output will be display in a split view instead. 

```lua
return {
  "nvim-telescope/telescope.nvim",
  tag = "0.1.5",
  dependencies = {
    'nvim-lua/plenary.nvim',
    'jonarrien/telescope-cmdline.nvim',
  },
  keys = {
    { ':', '<cmd>Telescope cmdline<cr>', desc = 'Cmdline' }
  },
  opts = {
    extensions = {
      cmdline = {
        overseer = {
          enabled = false
        }
      },
    }
  },
  config = function(_, opts)
    require("telescope").setup(opts)
    require("telescope").load_extension('cmdline')
  end,
}
```

**Comment by jonarrien** [comment]
I made some changes to disable `overseer.nvim` by defalt and other improvements. Please try version `0.2.0`.

**Comment by digital-deceit** [comment]
I executed Neovim with just these plugins. No options, autocmds, custom keymaps, etc.
I'm on WSL2, Neovim v0.11.0, but I have also tried in v0.10.0 and the issue persists.

I wonder if the plugin is looking through the whole binaries in my path including the Windows ones, I'm not sure, I'm still a newbie in all this computer science stuff.

```
return {
	"nvim-telescope/telescope.nvim",
	branch = "0.1.x",
	dependencies = {
		{ "nvim-lua/plenary.nvim" },
		{
			"nvim-telescope/telescope-fzf-native.nvim",
			build = "make",
			cond = function()
				return vim.fn.executable("make") == 1
			end,
		},
		{ "nvim-telescope/telescope-ui-select.nvim" },
		{ "nvim-telescope/telescope-file-browser.nvim" },
		{ "nvim-tree/nvim-web-devicons", enabled = vim.g.have_nerd_font },
		{ "jonarrien/telescope-cmdline.nvim" },
	},
	config = function()
		local telescope = require("telescope")
		local themes = require("telescope.themes")
		local actions = require("telescope.actions")

		telescope.setup({
			defaults = {
				mappings = {
					i = {
						["<c-down>"] = actions.cycle_history_next,
						["<c-up>"] = actions.cycle_history_prev,
					},
				},
			},
			extensions = {
				["ui-select"] = {
					themes.get_dropdown(),
				},
				["file_browser"] = {
					path = "%:p:h",
					cwd_to_path = true,
					layout_strategy = "center",
					layout_config = { height = 0.55, width = 0.45 },
					previewer = false,
					hijack_netrw = true,
					hidden = {
						file_browser = true,
						folder_browser = true,
					},
				},
				["cmdline"] = {
					overseer = {
						enabled = true,
					},
				},
			},
		})

		-- [[ Telescope extensions ]]
		pcall(telescope.load_extension, "fzf")
		pcall(telescope.load_extension, "ui-select")
		pcall(telescope.load_extension, "file_browser")
		pcall(telescope.load_extension, "cmdline")
	end,
}
```

Sorry for the late reply, I forgot I opened this issue.

**Comment by digital-deceit** [comment]
Update:
I managed to remove the interoperability between WSL and Windows so the Windows path cannot be reached inside WSL and the plugin started working, it is not freezing anymore.

I'll have to find a way in which I can use Windows paths, but excluded from Neovim.
