### ISSUE TITLE
Overseer.nvim dependancy

### ISSUE THREAD

**Issue by wlther** [jonarrien/telescope-cmdline.nvim#24]
`config.values.overseer.enabled` is `true` by default (in `lua/cmdline/config.lua`) but there are no mentions of this plugin in the README, causing errors if not installed.
Maybe it could be a good Idea to specify it more clearly or disable this setting by default or in case of a missing installation.
Anyway, thanks for the plugin !

**Comment by jonarrien** [comment]
Disabled overseer.nvim in `0.2.0`. By default it will run shell command (`:!cmd`) in split terminal.
