### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by PhilT** [jonarrien/telescope-cmdline.nvim#4]
I get a nil when trying to run `:Telescope cmdline` now. It looks like the export is missing maybe. I'm not too familiar with extensions but I'm trying to learn.

**Comment by PhilT** [comment]
I think it might be something on my end. Closing for now.

**Comment by PhilT** [comment]
No, actually I think there is a problem. The prior commit is fine.

**Comment by jonarrien** [comment]
Ensure you load the extension in Telescope: `require('telescope').load_extension('cmdline')`
https://github.com/nvim-telescope/telescope.nvim#extensions

**Comment by jonarrien** [comment]
Assuming loading extension fixed the issue.
