### ISSUE TITLE
feature: remap actions

### ISSUE THREAD

**Issue by Buer-Nahida** [jonarrien/telescope-cmdline.nvim#6]
I want remap actions
for example  I want remap tab to arrow down, but I can't use 
```lua
require("telescope").setup({
  extensions = {
    cmdline = {
      mappings = { ... },
    },
  },
})
```
to remap actions

I don't know if has remap feature, but I tryed mappings, keys, maps, and more possible names names, they're can't implement this feature too, so I writed this issues

**Comment by SR-MyStar** [comment]
q

**Comment by jonarrien** [comment]
There are a few mappings added in default config (`lua/cmdline/config.lua`), but mapping functionality is not very mature currently. 

It is part of the cmdline settings and didn't try with telescope, but I will definitely consider this. Thanks for raising.

**Comment by jonarrien** [comment]
This feature has been implemented. (sha: `a6fa069ae9beb5a429995c22a097284e63adbf45`)
