### ISSUE TITLE
Text background in selection is wrong

### ISSUE THREAD

**Issue by oredaze** [jonarrien/telescope-cmdline.nvim#9]
As the title says the background color of the selection, the part with text uses telescope's background (Normal?) not the selection.
You can even see it in your gif...

**Comment by jonarrien** [comment]
That is coming from the colorscheme. If you want to change the selection color, you can override the highlight `TelescopeSelection`.

**Comment by jonarrien** [comment]
It took me some time to figure out what you were referring to, but I found the issue. The selection color now displays properly.
